environment: dev
piano-tuner: true
controllers:
  - App\Controller\IndexController
  - App\Controller\TestController
annotations:
  Route: Pianissimo\Component\Routing\Annotation\Route
  Person: App\Annotation\Person